apiVersion: v1
kind: Service
metadata:
  name: grafana-tcp
  labels:
    app: grafana
spec:
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.1.14

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest-ubuntu
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
          env:
            - name: TZ
              value: America/Chicago
          ports:
            - containerPort: 3000
              name: grafana
      volumes:
        - name: data
          nfs:
            server: 192.168.1.113
            path: /volume2/grafana
